### ISSUE TITLE
[terraform-ibm-scc-da] Add support to create KMS key in external account

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-scc-da#107]
Changes should go into `solutions/instances` only..

- Add new optional variable `ibmcloud_kms_api_key`. This should be used in the kms provider block like so:
  ```
  provider "ibm" {
    alias            = "kms"
    ibmcloud_api_key = var.ibmcloud_kms_api_key != null ? var.ibmcloud_kms_api_key : var.ibmcloud_api_key
    region           = local.kms_region 
  }
  ```
- The `kms` module block should use the `kms` provider alias.
- Support creating cross account s2s auth policy (in KMS account)
- Review all of the variable descriptions and readme markdowns to ensure its clear that it supports KMS in a different account using the `ibmcloud_kms_api_key` variable.

**Comment by kierramarie** [comment]
following a method similar to this other PR: https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/230 which is based on Jordan Williams solution for observability da.

**Comment by kierramarie** [comment]
PR has been merged. Closing issue.
