### ISSUE TITLE
IAM permissions are incorrect for SCC WP agent DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-scc-da#115]
The tile shows this:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/assets/29608224/5b5f1a1e-11d5-4052-8194-4c558fd78aff)
![image](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/assets/29608224/b3193911-4bde-4a45-85c2-39339af2e65d)

However this is not correct - you would need Kubernetes editor role to deploy the agents to a kube cluster. AKA:
```
"iam_permissions": [
            {
              "service_name": "containers-kubernetes",
              "role_crns": [
                "crn:v1:bluemix:public:iam::::serviceRole:Manager",
                "crn:v1:bluemix:public:iam::::role:Viewer"
              ]
            }
          ],
```

**Comment by akocbek** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/pull/117
