### ISSUE TITLE
Add the ability to define the scope of SCC attachement

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-scc-da#139]
Currently the DA is hard coded to `"account"` scope. Suggest that we add support to define a resource group scope. Although currently attachements can only be scoped to 1 resource group (unless you use a do a full account with an exclude list), but in the future, I think they will support scoping more in the future, so maybe future proof it by using a list input.

**Comment by jor2** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/pull/148
