### ISSUE TITLE
Expose the ability to configure the SCC attachment schedule in the SCC DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-scc-da#149]
Configuring the schedule is a common use case (it is actually explicitly asked in the SCC UI when creating an attachment).
So we should expose 1 more variable for this in the SCC DA instead of always creating a daily schedule (default it to daily schedule though).

**Comment by in-1911** [comment]
Probably adding a simple value parameter for "default schedule" would be a good starting point.
Having a full structure for the attachment configuration (with parameters, exclusions, scheduling, etc) would be a long term goal, but if all the new attachments are created with the supplied default (e.g. set to 30 days) that would be enough to avoid higher cost of multiple daily scans.

**Comment by ocofaigh** [comment]
yep agree, thats the plan
