### ISSUE TITLE
papercut: wp estimates is misleading

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-scc-da#41]
To follow up with cost estimate. Tracking here for overall consolidation

In DA:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/assets/16447795/21cdbaaa-c967-4d3a-8fbe-89aa0768e705)

Cloud pricing:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/assets/16447795/7cd47415-af45-44e8-b6c5-5817c48c02f1)

**Comment by ocofaigh** [comment]
Workload protection was disabled for RAG stack, however here is what I see in the SCC DA itself:
![image](https://media.github.ibm.com/user/42199/files/265499c7-88a8-4329-af4d-26459d6f3169)

So looks like its good now - closing
