### ISSUE TITLE
papercut: scc estimate is misleading

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-scc-da#42]
### Description

DA:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/assets/16447795/bcc9ffb3-cb98-4cb9-ad6c-e9158a53ab79)

Cloud pricing:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/assets/16447795/2d069d75-5211-47cf-871c-e78ff16fa49b)

**Comment by ocofaigh** [comment]
Fixed
