### ISSUE TITLE
[terraform-ibm-scc-da] Add estimated-usage.yml to improve the calculated cost estimation

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-scc-da#84]
> We need to make a cost estimation change for the SCC and Observability DA’s. Both DAs thinks the estimated COS storage usage is 1TB, and that sounds grossly underestimated.
> We need to put in a yaml file like this : https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/main/estimated-usage.yml

**Comment by tyao117** [comment]
estimated-usage mapping is done by looking at the terraform plan and determining the objects being created.
